name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: template setup test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install system packages on Ubuntu
        if: ${{ runner.os == 'Linux' }}
        run: sudo apt-get install curl

      - name: Install system packages on macOS
        if: ${{ runner.os == 'macOS' }}
        run: brew install coreutils

      - name: Test plugin
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: erl -eval '{ok, Version} = file:read_file(filename:join([code:root_dir(), "releases", erlang:system_info(otp_release), "OTP_VERSION"])), io:fwrite(re:replace(Version, "(^\\s+)|(\\s+$)", "", [global,{return,list}])), halt().' -noshell
